name: XUMM.NET.SDK PR

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: windows-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build XUMM.NET.SDK
      run: dotnet build -p:PackageVersion=${{steps.tag.outputs.tag}} --configuration Release ./src/XUMM.NET.SDK/XUMM.NET.SDK.csproj
    - name: Run XUMM.NET.SDK Tests
      run: dotnet test ./src/XUMM.NET.SDK.Tests/XUMM.NET.SDK.Tests.csproj